In [10]:
import pandas as pd
df=pd.read_csv(r"C:\Users\onc\Downloads\encoding_practice.csv")
df.head()

,Customer_ID,City,Payment_Method,Education_Level,Service_Rating,Purchase_Decision
0,1,Paris,PayPal,Master,Poor,Yes
1,2,Berlin,PayPal,Bachelor,Poor,Yes
2,3,Tokyo,PayPal,Master,Poor,Yes
3,4,Berlin,Debit Card,Master,Good,Yes
4,5,Berlin,Debit Card,Bachelor,Good,No

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Customer_ID        200 non-null    int64
 1   City               200 non-null    object
 2   Payment_Method     200 non-null    object
 3   Education_Level    200 non-null    object
 4   Service_Rating     200 non-null    object
 5   Purchase_Decision  200 non-null    object
dtypes: int64(1), object(5)
memory usage: 9.5+ KB

In [12]:
df.describe()

       Customer_ID
count   200.000000
mean    100.500000
std      57.879185
min       1.000000
25%      50.750000
50%     100.500000
75%     150.250000
max     200.000000

In [14]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
195    False
196    False
197    False
198    False
199    False
Length: 200, dtype: bool

In [18]:
# Check data types
print("Data Types:")
print(df.dtypes)

Data Types:
Customer_ID           int64
City                 object
Payment_Method       object
Education_Level      object
Service_Rating       object
Purchase_Decision    object
dtype: object

In [19]:
print(df.columns.tolist())

['Customer_ID', 'City', 'Payment_Method', 'Education_Level', 'Service_Rating', 'Purchase_Decision']

In [20]:
print("\n--- Unique values in each categorical column ---")
for col in ['Education_Level', 'Service_Rating','Purchase_Decision']:
    print(f"\n{col}: {df[col].unique()}")

--- Unique values in each categorical column ---

Education_Level: ['Master' 'Bachelor' 'High School' 'PhD']

Service_Rating: ['Poor' 'Good' 'Excellent' 'Fair']

Purchase_Decision: ['Yes' 'No']

In [22]:
#Ordinal encoding..
from sklearn.preprocessing import OrdinalEncoder
education_order = ['High School','Bachelor','Master','PhD']		
service_order = ['Poor', 'Fair', 'Good', 'Excellent'] 
oe = OrdinalEncoder(categories=[education_order,service_order])
df[['Education_Level','Service_Rating']] = oe.fit_transform(df[['Education_Level','Service_Rating']])

print("After Ordinal Encoding:")
print("Subscription mapping: High School=0,  Bachelor=1  ,Master=2  ,PhD=3")
print("\nRating mapping:      Poor=0, Fair=1, Good=2, Excellent=3")
print()
df

After Ordinal Encoding:
Subscription mapping: High School=0,  Bachelor=1  ,Master=2  ,PhD=3

Rating mapping:      Poor=0, Fair=1, Good=2, Excellent=3

,Customer_ID,City,Payment_Method,Education_Level,Service_Rating,Purchase_Decision
0,1,Paris,PayPal,2.0,0.0,Yes
1,2,Berlin,PayPal,1.0,0.0,Yes
2,3,Tokyo,PayPal,2.0,0.0,Yes
3,4,Berlin,Debit Card,2.0,2.0,Yes
4,5,Berlin,Debit Card,1.0,2.0,No
...,...,...,...,...,...,...
195,196,Tokyo,Cash,3.0,3.0,Yes
196,197,Tokyo,PayPal,3.0,3.0,No
197,198,New York,Cash,1.0,0.0,No
198,199,Berlin,Debit Card,2.0,2.0,Yes
199,200,Paris,PayPal,3.0,0.0,Yes

In [23]:
#Label encoding...
df[['Purchase_Decision']]

    Purchase_Decision
0                 Yes
1                 Yes
2                 Yes
3                 Yes
4                  No
..                ...
195               Yes
196                No
197                No
198               Yes
199               Yes

[200 rows x 1 columns]

In [24]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['Purchase_Decision'] = le.fit_transform(df['Purchase_Decision'])

print("Label Encoding mapping:")
for i , value in enumerate(le.classes_):
    print(f"  {i} → {value}")

print("\nDataset after Label Encoding target:")
df

Label Encoding mapping:
  0 → No
  1 → Yes

Dataset after Label Encoding target:

,Customer_ID,City,Payment_Method,Education_Level,Service_Rating,Purchase_Decision
0,1,Paris,PayPal,2.0,0.0,1
1,2,Berlin,PayPal,1.0,0.0,1
2,3,Tokyo,PayPal,2.0,0.0,1
3,4,Berlin,Debit Card,2.0,2.0,1
4,5,Berlin,Debit Card,1.0,2.0,0
...,...,...,...,...,...,...
195,196,Tokyo,Cash,3.0,3.0,1
196,197,Tokyo,PayPal,3.0,3.0,0
197,198,New York,Cash,1.0,0.0,0
198,199,Berlin,Debit Card,2.0,2.0,1
199,200,Paris,PayPal,3.0,0.0,1

In [25]:
#One hot encoding....
df[['City','Payment_Method']]

         City Payment_Method
0       Paris         PayPal
1      Berlin         PayPal
2       Tokyo         PayPal
3      Berlin     Debit Card
4      Berlin     Debit Card
..        ...            ...
195     Tokyo           Cash
196     Tokyo         PayPal
197  New York           Cash
198    Berlin     Debit Card
199     Paris         PayPal

[200 rows x 2 columns]

In [26]:
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder(drop='first', sparse_output=False)

# Fit and transform City and Payment_Method
encoded_data = ohe.fit_transform(df[['City', 'Payment_Method']])

# Get names of new columns
encoded_columns = ohe.get_feature_names_out(['City', 'Payment_Method'])

print("New columns created:")
print(encoded_columns)

# Convert to DataFrame
encoded_df = pd.DataFrame(
    encoded_data.astype(int),
    columns=encoded_columns,
    index=df.index
)

print("\nOne-Hot Encoded Data:")
print(encoded_df)

New columns created:
['City_London' 'City_New York' 'City_Paris' 'City_Tokyo'
 'Payment_Method_Credit Card' 'Payment_Method_Debit Card'
 'Payment_Method_PayPal']

One-Hot Encoded Data:
     City_London  City_New York  City_Paris  City_Tokyo  \
0              0              0           1           0
1              0              0           0           0
2              0              0           0           1
3              0              0           0           0
4              0              0           0           0
..           ...            ...         ...         ...
195            0              0           0           1
196            0              0           0           1
197            0              1           0           0
198            0              0           0           0
199            0              0           1           0

     Payment_Method_Credit Card  Payment_Method_Debit Card  \
0                             0                          0
1                             0                          0
2                             0                          0
3                             0                          1
4                             0                          1
..                          ...                        ...
195                           0                          0
196                           0                          0
197                           0                          0
198                           0                          1
199                           0                          0

     Payment_Method_PayPal
0                        1
1                        1
2                        1
3                        0
4                        0
..                     ...
195                      0
196                      1
197                      0
198                      0
199                      1

[200 rows x 7 columns]

In [27]:
import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OrdinalEncoder, OneHotEncoder

# Load your dataset (IMPORTANT)
df = pd.read_csv("encoding_practice.csv")   # change file name if needed

# Ordinal category order
education_order = ['High School', 'Bachelor', 'Master', 'PhD']
rating_order = ['Poor', 'Fair', 'Good', 'Excellent']

# Column Transformer
ct = ColumnTransformer(
    transformers=[
        (
            'ordinal',
            OrdinalEncoder(categories=[education_order, rating_order]),
            ['Education_Level', 'Service_Rating']
        ),
        (
            'onehot',
            OneHotEncoder(drop='first', sparse_output=False),
            ['City', 'Payment_Method']
        )
    ],
    remainder='passthrough'
)

# Fit and transform data
encoded_data = ct.fit_transform(df)

# Get One-Hot column names
onehot_cols = ct.named_transformers_['onehot'].get_feature_names_out(
    ['City', 'Payment_Method']
)

# Final column names
all_columns = (
    ['Education_Level', 'Service_Rating']
    + list(onehot_cols)
    + ['Customer_ID', 'Purchase_Decision']
)

# Create final DataFrame
encoded_df = pd.DataFrame(encoded_data, columns=all_columns)

print(encoded_df.head())

  Education_Level Service_Rating City_London City_New York City_Paris  \
0             2.0            0.0         0.0           0.0        1.0
1             1.0            0.0         0.0           0.0        0.0
2             2.0            0.0         0.0           0.0        0.0
3             2.0            2.0         0.0           0.0        0.0
4             1.0            2.0         0.0           0.0        0.0

  City_Tokyo Payment_Method_Credit Card Payment_Method_Debit Card  \
0        0.0                        0.0                       0.0
1        0.0                        0.0                       0.0
2        1.0                        0.0                       0.0
3        0.0                        0.0                       1.0
4        0.0                        0.0                       1.0

  Payment_Method_PayPal Customer_ID Purchase_Decision
0                   1.0           1               Yes
1                   1.0           2               Yes
2                   1.0           3               Yes
3                   0.0           4               Yes
4                   0.0           5                No