In [11]:
#DAy 1 of learning pandas
#June 2

In [12]:
# Series:1D data structure
# Has index

In [3]:
#creating Series with list
import pandas as pd
l=[1,2,3,4,5,6,7,8]
s=pd.Series(l)
s

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
dtype: int64

In [4]:
# we can also change index by..
l=[1,2,3,4,5,6,7,8]
s=pd.Series(l,index=['a','b','c','d','e','f','g','h'])
s

a    1
b    2
c    3
d    4
e    5
f    6
g    7
h    8
dtype: int64

In [5]:
# creating series with array
import numpy as np
a=np.array([80,20,78])
s=pd.Series(a)#Convert array to a Pandas Series
s

0    80
1    20
2    78
dtype: int64

In [6]:
s=pd.Series(['suraj','aman','apil','sabal'],index=['a','b','c','d'])
s

a    suraj
b     aman
c     apil
d    sabal
dtype: object

In [7]:
#return all index values
s.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [8]:
#using array attributes(returns all data in pandas array)
s.array

<NumpyExtensionArray>
['suraj', 'aman', 'apil', 'sabal']
Length: 4, dtype: object

In [9]:
#using dtype attributes gives what is the datatypes of elements of this series.
s.dtypes

dtype('O')

In [10]:
#shape represent the rows.
s.shape

(4,)

In [11]:
#return the dimension of the series
s.ndim

1

In [12]:
#returns value of series in numpy array
s.values

array(['suraj', 'aman', 'apil', 'sabal'], dtype=object)

In [13]:
#Gives the  total number of element in the series.
s.size

4

In [14]:
#using empty attributes gives boolean values(if series is empty then True and ...
s.empty

False

In [15]:
s

a    suraj
b     aman
c     apil
d    sabal
dtype: object

In [16]:
s.at['c']#'a' label ma vako value dinxa series bata

'apil'

In [17]:
s.iat[3]#index ma vako value dinxa series bata

'sabal'

In [18]:
# Mathematical operation in series.
import pandas as pd
s1=pd.Series([1,2,3])
s2=pd.Series([2,3,4])

In [19]:
s1

0    1
1    2
2    3
dtype: int64

In [20]:
s2

0    2
1    3
2    4
dtype: int64

In [21]:
#add
s1+s2
#s1.add(s2)

0    3
1    5
2    7
dtype: int64

In [22]:
s1**s2

0     1
1     8
2    81
dtype: int64

In [23]:
s1>s2

0    False
1    False
2    False
dtype: bool

In [24]:
s1!=s2

0    True
1    True
2    True
dtype: bool

In [25]:
#Getting values from series
s=pd.Series([1,3,4,6])
s

0    1
1    3
2    4
3    6
dtype: int64

In [26]:
#getting index 3 value
print(s[3])

6

In [27]:
#Getting index 1 and 2 element.
s[1:3]

1    3
2    4
dtype: int64

In [28]:
s.index=['a','b','c','d']
s

a    1
b    3
c    4
d    6
dtype: int64

In [29]:
print(s['d'])

6

In [30]:
s.unique

<bound method Series.unique of a    1
b    3
c    4
d    6
dtype: int64>

In [31]:
s.mean

<bound method Series.mean of a    1
b    3
c    4
d    6
dtype: int64>

In [32]:
s.min

<bound method Series.min of a    1
b    3
c    4
d    6
dtype: int64>

In [33]:

s.max

<bound method Series.max of a    1
b    3
c    4
d    6
dtype: int64>

In [34]:
#making data frame by reading excel.
df=pd.read_excel(r"C:\Users\onc\Downloads\excel_df 1 (1).xlsx")
df

     name  roll  age
0   miraj     1   13
1   sabal     2   34
2  sarita     3   32
3  rashmi     4   54
4  sabnam     5   32

In [35]:
df=pd.read_csv(r"C:\Users\onc\Downloads\new_data 1 (1).csv")
df

Empty DataFrame
Columns: [{"name":{"a":"miraj", b:"sabal", c:"sarita", d:"rashmi", e:"sabnam"}, roll:{"a":1, b:2, c:3, d:4, e:5}, age:{"a":13, b:34, c:32, d:54, e:32}}]
Index: []

In [36]:
# making data frame by using dictionary
dict={'name':['miraj','sabal','sarita','rashmi','sabnam'],
      'roll':[1,2,3,4,5],'age':[13,34,32,54,32]}
df=pd.DataFrame(dict)
df

     name  roll  age
0   miraj     1   13
1   sabal     2   34
2  sarita     3   32
3  rashmi     4   54
4  sabnam     5   32

In [37]:
df.T

          0      1       2       3       4
name  miraj  sabal  sarita  rashmi  sabnam
roll      1      2       3       4       5
age      13     34      32      54      32

In [38]:
'''Similar to loc,both need label based lookups,
use at if you only need to get or set a single value in a dataframe or series'''
print(df.at[1,'age'])

34

In [39]:
df.index#gives the row index of the dataframe
df.index=['a','b','c','d','e']#we can also change index like this
df

     name  roll  age
a   miraj     1   13
b   sabal     2   34
c  sarita     3   32
d  rashmi     4   54
e  sabnam     5   32

In [40]:
df.axes#give columns row names and columns name
#df.axes[0]#row names
#df.axes[1]#column names

[Index(['a', 'b', 'c', 'd', 'e'], dtype='object'),
 Index(['name', 'roll', 'age'], dtype='object')]

In [41]:
df.columns#gives columns names

Index(['name', 'roll', 'age'], dtype='object')

In [42]:
df.head

<bound method NDFrame.head of      name  roll  age
a   miraj     1   13
b   sabal     2   34
c  sarita     3   32
d  rashmi     4   54
e  sabnam     5   32>

In [43]:
df.info

<bound method DataFrame.info of      name  roll  age
a   miraj     1   13
b   sabal     2   34
c  sarita     3   32
d  rashmi     4   54
e  sabnam     5   32>

In [44]:
df.describe

<bound method NDFrame.describe of      name  roll  age
a   miraj     1   13
b   sabal     2   34
c  sarita     3   32
d  rashmi     4   54
e  sabnam     5   32>

In [45]:
df.shape

(5, 3)

In [46]:
df.columns

Index(['name', 'roll', 'age'], dtype='object')

In [47]:
df.dtypes

name    object
roll     int64
age      int64
dtype: object

In [48]:
df.ndim

2

In [49]:
df.size#give the number of elements in the data frame

15

In [50]:
df.value_counts()#returns how many times each unique values is repeated in a series

name    roll  age
miraj   1     13     1
rashmi  4     54     1
sabal   2     34     1
sabnam  5     32     1
sarita  3     32     1
Name: count, dtype: int64

In [51]:
df['age'].value_counts()

age
32    2
13    1
34    1
54    1
Name: count, dtype: int64

In [52]:
df.values#converts numpy dataframe into numpy array..

array([['miraj', 1, 13],
       ['sabal', 2, 34],
       ['sarita', 3, 32],
       ['rashmi', 4, 54],
       ['sabnam', 5, 32]], dtype=object)

In [53]:
#converts the dataframe into dictionary
df.to_dict()

{'name': {'a': 'miraj',
  'b': 'sabal',
  'c': 'sarita',
  'd': 'rashmi',
  'e': 'sabnam'},
 'roll': {'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5},
 'age': {'a': 13, 'b': 34, 'c': 32, 'd': 54, 'e': 32}}

In [54]:
#we can also convert dataframe into json
df.to_json(r"C:\Users\onc\Downloads\new_data 1 (1).csv")

In [55]:
#reading from json file.
df=pd.read_json(r"C:\Users\onc\Downloads\new_data 1 (1).csv")
df

     name  roll  age
a   miraj     1   13
b   sabal     2   34
c  sarita     3   32
d  rashmi     4   54
e  sabnam     5   32

In [56]:
df.index=['b','a','g','c','d']
#sorting the items on the basis of index in ascending way
df.sort_index(ascending=False)

     name  roll  age
g  sarita     3   32
d  sabnam     5   32
c  rashmi     4   54
b   miraj     1   13
a   sabal     2   34

In [57]:
#setting the existing column to index
df.set_index('roll')

        name  age
roll
1      miraj   13
2      sabal   34
3     sarita   32
4     rashmi   54
5     sabnam   32

In [58]:
#reset of index to default one
df.reset_index()

  index    name  roll  age
0     b   miraj     1   13
1     a   sabal     2   34
2     g  sarita     3   32
3     c  rashmi     4   54
4     d  sabnam     5   32

In [59]:
df.reset_index(drop=True)#if we don't want extra index in column we can do  this..

     name  roll  age
0   miraj     1   13
1   sabal     2   34
2  sarita     3   32
3  rashmi     4   54
4  sabnam     5   32

In [60]:
#DataFrame which consists the NaN values
data = {'Name':['John','Emma',np.nan],
        'Age':[25,np.nan,30],
        'Height':[175,162,np.nan]}
df=pd.DataFrame(data)
df

   Name   Age  Height
0  John  25.0   175.0
1  Emma   NaN   162.0
2   NaN  30.0     NaN

In [61]:
#Replacing the NaN values with None
df.replace(np.nan,None,inplace=True)
df

   Name   Age Height
0  John  25.0  175.0
1  Emma  None  162.0
2  None  30.0   None

In [62]:
#replace Emma with Miraj
df.replace('Emma','Miraj',inplace=True)
df

    Name   Age Height
0   John  25.0  175.0
1  Miraj  None  162.0
2   None  30.0   None

In [63]:
#Renaming column labels and row labels
col_corr = {'Name':'NAME1','Age':'AGE1','Height':'HEIGHT1'}
row_corr= {0:'a',1:'b',2:'c'}
df.rename(index=row_corr,columns=col_corr,inplace=True)
df

   NAME1  AGE1 HEIGHT1
a   John  25.0   175.0
b  Miraj  None   162.0
c   None  30.0    None

In [64]:
#performing the query() fnction in the dataframe.

#Create a sample DataFrame
data = {'Name':['John','Emma','Michael','Sophia'],
        'Age':[25,28,22,30],
        'Height':[175,162,180,168]}
df=pd.DataFrame(data)
#Print the original DataFrame
print('Original DataFrame:')
print(df)

#Perform different types of queries...
filtered_df1 = df.query('Age > 25 and Height < 170') #Numeric comparison
filtered_df2 = df.query("Name == 'John'") #Name column ma John vako row dinxa
filtered_df3 = df.query("Name in ['John','Emma']") #select rows ehere Name is either 'John' or 'Emma'
filtered_df4= df.query('not Height <= 168') #select rows where height is not lesser equal to 168
filtered_df5= df.query("Name.str.startswith('S')") #Select rows where Name starts with the letter 'M'

#print the filtered DataFrame DataFrame

print('\n')
print(filtered_df1)
print('\n')
print(filtered_df2)
print('\n')
print(filtered_df3)
print('\n')
print(filtered_df4)
print('\n')
print(filtered_df5)

Original DataFrame:
      Name  Age  Height
0     John   25     175
1     Emma   28     162
2  Michael   22     180
3   Sophia   30     168


     Name  Age  Height
1    Emma   28     162
3  Sophia   30     168


   Name  Age  Height
0  John   25     175


   Name  Age  Height
0  John   25     175
1  Emma   28     162


      Name  Age  Height
0     John   25     175
2  Michael   22     180


     Name  Age  Height
3  Sophia   30     168

In [65]:
#create a sample dataFrame with missing values
data = {'Name':['John','Emma',np.nan],
        'Age':[25,np.nan,30],
        'Height':[175,162,np.nan]}
df=pd.DataFrame(data)
df

   Name   Age  Height
0  John  25.0   175.0
1  Emma   NaN   162.0
2   NaN  30.0     NaN

In [66]:
df['Name'].notna() #returns the boolean value true  if there is value in dataframe

0     True
1     True
2    False
Name: Name, dtype: bool

In [67]:
df['Name'].isnull() #return true if there is null value

0    False
1    False
2     True
Name: Name, dtype: bool

In [68]:
#returns the rows which have values
df[df['Name'].notna()]

   Name   Age  Height
0  John  25.0   175.0
1  Emma   NaN   162.0

In [69]:
dict={'name':['miraj','sabal','sarita','rashmi','sabnam'],
      'roll':[1,2,3,4,5],'age':[13,34,32,54,32]}
df=pd.DataFrame(dict)
df

     name  roll  age
0   miraj     1   13
1   sabal     2   34
2  sarita     3   32
3  rashmi     4   54
4  sabnam     5   32

In [70]:
s=df.nsmallest(3,'age') #age column ko 3 ota smallest value dinxa
s

     name  roll  age
0   miraj     1   13
2  sarita     3   32
4  sabnam     5   32

In [71]:
s=df.nlargest(3,'age') #age column ko 3 ota largest value dinxa
s

     name  roll  age
3  rashmi     4   54
1   sabal     2   34
2  sarita     3   32

In [72]:
df.info()#provide a concise summary ,including data types,non null....

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    5 non-null      object
 1   roll    5 non-null      int64
 2   age     5 non-null      int64
dtypes: int64(2), object(1)
memory usage: 252.0+ bytes

In [73]:
df.describe()
#generates descriptive statistics of a dataframes,including count,mean,standard deviation,min,max and quartiles values...

           roll        age
count  5.000000   5.000000
mean   3.000000  33.000000
std    1.581139  14.525839
min    1.000000  13.000000
25%    2.000000  32.000000
50%    3.000000  32.000000
75%    4.000000  34.000000
max    5.000000  54.000000

In [74]:
df.count()#return  not null values in each column

name    5
roll    5
age     5
dtype: int64

In [75]:
#copying the dataframe into m
m=df.copy()
m

     name  roll  age
0   miraj     1   13
1   sabal     2   34
2  sarita     3   32
3  rashmi     4   54
4  sabnam     5   32

In [76]:
df.nunique()#kati oota unique value xa  each column ma tyo dinxa...

name    5
roll    5
age     4
dtype: int64

In [77]:
# Imp Functions,Accessing Values,Slicing in data Frame

df = pd.read_excel(r"C:\Users\onc\Downloads\example 1 (1).xlsx" )
df

              Name  Age  Roll  Salary            Address
0         John Doe   27   101   50000    123 Main Street
1       Jane Smith   32   102   65000     456 Elm Avenue
2    David Johnson   41   103   80000       789 Oak Lane
3   Sarah Williams   29   104   55000      321 Pine Road
4    Michael Brown   35   105   70000    654 Maple Drive
5      Emily Davis   24   106   45000   987 Cedar Street
6     James Wilson   38   107   75000    543 Birch Court
7  Jennifer Taylor   31   108   60000    876 Walnut Lane
8  Robert Anderson   26   109   48000  234 Spruce Avenue
9   Jessica Thomas   33   110   68000    567 Cherry Lane

In [78]:
# We can also give index like this...
df = pd.read_excel(r"C:\Users\onc\Downloads\example 1 (1).xlsx" )
df.set_index('Name',inplace=True) 
df

                 Age  Roll  Salary            Address
Name
John Doe          27   101   50000    123 Main Street
Jane Smith        32   102   65000     456 Elm Avenue
David Johnson     41   103   80000       789 Oak Lane
Sarah Williams    29   104   55000      321 Pine Road
Michael Brown     35   105   70000    654 Maple Drive
Emily Davis       24   106   45000   987 Cedar Street
James Wilson      38   107   75000    543 Birch Court
Jennifer Taylor   31   108   60000    876 Walnut Lane
Robert Anderson   26   109   48000  234 Spruce Avenue
Jessica Thomas    33   110   68000    567 Cherry Lane

In [79]:
# To make data frame from the specific column while reading csv and excel file...
df = pd.read_excel(r'C:\Users\onc\Downloads\example 1 (1).xlsx' ,index_col = 'Roll', usecols=['Name','Roll','Age'])
df

                 Name  Age
Roll
101          John Doe   27
102        Jane Smith   32
103     David Johnson   41
104    Sarah Williams   29
105     Michael Brown   35
106       Emily Davis   24
107      James Wilson   38
108   Jennifer Taylor   31
109   Robert Anderson   26
110    Jessica Thomas   33

In [80]:
# To get only specific rows in data frame(nrows)
df = pd.read_excel(r'C:\Users\onc\Downloads\example 1 (1).xlsx' ,index_col = 'Roll', usecols=['Name','Roll','Age'],nrows=2)
df

            Name  Age
Roll
101     John Doe   27
102   Jane Smith   32

In [81]:
df = pd.read_excel(r'C:\Users\onc\Downloads\example 1 (1).xlsx' ,index_col = 'Roll', usecols=['Name','Roll','Age'] )
df

                 Name  Age
Roll
101          John Doe   27
102        Jane Smith   32
103     David Johnson   41
104    Sarah Williams   29
105     Michael Brown   35
106       Emily Davis   24
107      James Wilson   38
108   Jennifer Taylor   31
109   Robert Anderson   26
110    Jessica Thomas   33

In [82]:
df.head()

                Name  Age
Roll
101         John Doe   27
102       Jane Smith   32
103    David Johnson   41
104   Sarah Williams   29
105    Michael Brown   35

In [83]:
df.tail()

                 Name  Age
Roll
106       Emily Davis   24
107      James Wilson   38
108   Jennifer Taylor   31
109   Robert Anderson   26
110    Jessica Thomas   33

In [84]:
df.sample(5)

                 Name  Age
Roll
105     Michael Brown   35
104    Sarah Williams   29
108   Jennifer Taylor   31
107      James Wilson   38
106       Emily Davis   24

In [85]:
#To get particular column from dataframe
df['Name']

Roll
101           John Doe
102         Jane Smith
103      David Johnson
104     Sarah Williams
105      Michael Brown
106        Emily Davis
107       James Wilson
108    Jennifer Taylor
109    Robert Anderson
110     Jessica Thomas
Name: Name, dtype: object

In [86]:
# To get specific value from the column of dataframe
df.iloc[5]['Name']

'Emily Davis'

In [87]:
#to get only 5 value from columns/series
df['Name'].head()

Roll
101          John Doe
102        Jane Smith
103     David Johnson
104    Sarah Williams
105     Michael Brown
Name: Name, dtype: object

In [88]:
df

                 Name  Age
Roll
101          John Doe   27
102        Jane Smith   32
103     David Johnson   41
104    Sarah Williams   29
105     Michael Brown   35
106       Emily Davis   24
107      James Wilson   38
108   Jennifer Taylor   31
109   Robert Anderson   26
110    Jessica Thomas   33

In [89]:
#if we have to access the two columns from the data frae the we have to use nexted list
df[['Name','Age']]

                 Name  Age
Roll
101          John Doe   27
102        Jane Smith   32
103     David Johnson   41
104    Sarah Williams   29
105     Michael Brown   35
106       Emily Davis   24
107      James Wilson   38
108   Jennifer Taylor   31
109   Robert Anderson   26
110    Jessica Thomas   33

In [90]:
# Slicing,---Default slicing is row,  col slice can be done using .loc
df[2:7]

                Name  Age
Roll
103    David Johnson   41
104   Sarah Williams   29
105    Michael Brown   35
106      Emily Davis   24
107     James Wilson   38

In [91]:
# now getting column from the slicing..
df[2:7] ['Age']

Roll
103    41
104    29
105    35
106    24
107    38
Name: Age, dtype: int64

In [92]:
#with two step slicing
df[0:10:2]

                 Name  Age
Roll
101          John Doe   27
103     David Johnson   41
105     Michael Brown   35
107      James Wilson   38
109   Robert Anderson   26

In [93]:
df[['Name','Age']][2:9]

                 Name  Age
Roll
103     David Johnson   41
104    Sarah Williams   29
105     Michael Brown   35
106       Emily Davis   24
107      James Wilson   38
108   Jennifer Taylor   31
109   Robert Anderson   26

In [94]:
#to get specific series row as series
df.iloc[2] #gives index 2 row value as series

Name    David Johnson
Age                41
Name: 103, dtype: object

In [99]:
df.iloc[3]['Age']#Gives  only age value of index 2 row

np.int64(29)

In [101]:
df.loc[107]# use index column to print  row

Name    James Wilson
Age               38
Name: 107, dtype: object

In [ ]:
#Sorting the dataFrame on the bis values of column ascending and descending...

In [103]:
df = pd.read_excel(r"C:\Users\onc\Downloads\example 1 (1).xlsx" )
df.set_index('Name',inplace=True) 
df

                 Age  Roll  Salary            Address
Name
John Doe          27   101   50000    123 Main Street
Jane Smith        32   102   65000     456 Elm Avenue
David Johnson     41   103   80000       789 Oak Lane
Sarah Williams    29   104   55000      321 Pine Road
Michael Brown     35   105   70000    654 Maple Drive
Emily Davis       24   106   45000   987 Cedar Street
James Wilson      38   107   75000    543 Birch Court
Jennifer Taylor   31   108   60000    876 Walnut Lane
Robert Anderson   26   109   48000  234 Spruce Avenue
Jessica Thomas    33   110   68000    567 Cherry Lane

In [104]:
#  Sorting Ascending wise
df.sort_values('Salary')

                 Age  Roll  Salary            Address
Name
Emily Davis       24   106   45000   987 Cedar Street
Robert Anderson   26   109   48000  234 Spruce Avenue
John Doe          27   101   50000    123 Main Street
Sarah Williams    29   104   55000      321 Pine Road
Jennifer Taylor   31   108   60000    876 Walnut Lane
Jane Smith        32   102   65000     456 Elm Avenue
Jessica Thomas    33   110   68000    567 Cherry Lane
Michael Brown     35   105   70000    654 Maple Drive
James Wilson      38   107   75000    543 Birch Court
David Johnson     41   103   80000       789 Oak Lane

In [105]:
#  Sorting Descending wise
df.sort_values('Salary',ascending=False)

                 Age  Roll  Salary            Address
Name
David Johnson     41   103   80000       789 Oak Lane
James Wilson      38   107   75000    543 Birch Court
Michael Brown     35   105   70000    654 Maple Drive
Jessica Thomas    33   110   68000    567 Cherry Lane
Jane Smith        32   102   65000     456 Elm Avenue
Jennifer Taylor   31   108   60000    876 Walnut Lane
Sarah Williams    29   104   55000      321 Pine Road
John Doe          27   101   50000    123 Main Street
Robert Anderson   26   109   48000  234 Spruce Avenue
Emily Davis       24   106   45000   987 Cedar Street

In [106]:
df['Roll']

Name
John Doe           101
Jane Smith         102
David Johnson      103
Sarah Williams     104
Michael Brown      105
Emily Davis        106
James Wilson       107
Jennifer Taylor    108
Robert Anderson    109
Jessica Thomas     110
Name: Roll, dtype: int64

In [107]:
df['Roll'].sort_values(ascending=False)

Name
Jessica Thomas     110
Robert Anderson    109
Jennifer Taylor    108
James Wilson       107
Emily Davis        106
Michael Brown      105
Sarah Williams     104
David Johnson      103
Jane Smith         102
John Doe           101
Name: Roll, dtype: int64

In [152]:
# Adding and Dropping the column in DataFrame..


df = pd.read_excel(r"C:\Users\onc\Downloads\example 1 (1).xlsx" )
df.set_index('Name',inplace=True) 
df

                 Age  Roll  Salary            Address
Name
John Doe          27   101   50000    123 Main Street
Jane Smith        32   102   65000     456 Elm Avenue
David Johnson     41   103   80000       789 Oak Lane
Sarah Williams    29   104   55000      321 Pine Road
Michael Brown     35   105   70000    654 Maple Drive
Emily Davis       24   106   45000   987 Cedar Street
James Wilson      38   107   75000    543 Birch Court
Jennifer Taylor   31   108   60000    876 Walnut Lane
Robert Anderson   26   109   48000  234 Spruce Avenue
Jessica Thomas    33   110   68000    567 Cherry Lane

In [153]:
#Adding new column gender.
df['Gender']=['m','f','m','f','m','f','m','m','m','f']
df

                 Age  Roll  Salary            Address Gender
Name
John Doe          27   101   50000    123 Main Street      m
Jane Smith        32   102   65000     456 Elm Avenue      f
David Johnson     41   103   80000       789 Oak Lane      m
Sarah Williams    29   104   55000      321 Pine Road      f
Michael Brown     35   105   70000    654 Maple Drive      m
Emily Davis       24   106   45000   987 Cedar Street      f
James Wilson      38   107   75000    543 Birch Court      m
Jennifer Taylor   31   108   60000    876 Walnut Lane      m
Robert Anderson   26   109   48000  234 Spruce Avenue      m
Jessica Thomas    33   110   68000    567 Cherry Lane      f

In [154]:
df['roll+age']=df['Age']+df['Roll'] #2 oota series return hunxa ra sum hunxa ani naya column banxa
df

                 Age  Roll  Salary            Address Gender  roll+age
Name
John Doe          27   101   50000    123 Main Street      m       128
Jane Smith        32   102   65000     456 Elm Avenue      f       134
David Johnson     41   103   80000       789 Oak Lane      m       144
Sarah Williams    29   104   55000      321 Pine Road      f       133
Michael Brown     35   105   70000    654 Maple Drive      m       140
Emily Davis       24   106   45000   987 Cedar Street      f       130
James Wilson      38   107   75000    543 Birch Court      m       145
Jennifer Taylor   31   108   60000    876 Walnut Lane      m       139
Robert Anderson   26   109   48000  234 Spruce Avenue      m       135
Jessica Thomas    33   110   68000    567 Cherry Lane      f       143

In [155]:
df.drop(columns='roll+age')#but dont drop in original dataframa.

                 Age  Roll  Salary            Address Gender
Name
John Doe          27   101   50000    123 Main Street      m
Jane Smith        32   102   65000     456 Elm Avenue      f
David Johnson     41   103   80000       789 Oak Lane      m
Sarah Williams    29   104   55000      321 Pine Road      f
Michael Brown     35   105   70000    654 Maple Drive      m
Emily Davis       24   106   45000   987 Cedar Street      f
James Wilson      38   107   75000    543 Birch Court      m
Jennifer Taylor   31   108   60000    876 Walnut Lane      m
Robert Anderson   26   109   48000  234 Spruce Avenue      m
Jessica Thomas    33   110   68000    567 Cherry Lane      f

In [156]:
df

                 Age  Roll  Salary            Address Gender  roll+age
Name
John Doe          27   101   50000    123 Main Street      m       128
Jane Smith        32   102   65000     456 Elm Avenue      f       134
David Johnson     41   103   80000       789 Oak Lane      m       144
Sarah Williams    29   104   55000      321 Pine Road      f       133
Michael Brown     35   105   70000    654 Maple Drive      m       140
Emily Davis       24   106   45000   987 Cedar Street      f       130
James Wilson      38   107   75000    543 Birch Court      m       145
Jennifer Taylor   31   108   60000    876 Walnut Lane      m       139
Robert Anderson   26   109   48000  234 Spruce Avenue      m       135
Jessica Thomas    33   110   68000    567 Cherry Lane      f       143

In [157]:
df=df.drop(columns='roll+age')# to drop from main dataframe or we can also use inplace..
df

                 Age  Roll  Salary            Address Gender
Name
John Doe          27   101   50000    123 Main Street      m
Jane Smith        32   102   65000     456 Elm Avenue      f
David Johnson     41   103   80000       789 Oak Lane      m
Sarah Williams    29   104   55000      321 Pine Road      f
Michael Brown     35   105   70000    654 Maple Drive      m
Emily Davis       24   106   45000   987 Cedar Street      f
James Wilson      38   107   75000    543 Birch Court      m
Jennifer Taylor   31   108   60000    876 Walnut Lane      m
Robert Anderson   26   109   48000  234 Spruce Avenue      m
Jessica Thomas    33   110   68000    567 Cherry Lane      f

In [158]:
df

                 Age  Roll  Salary            Address Gender
Name
John Doe          27   101   50000    123 Main Street      m
Jane Smith        32   102   65000     456 Elm Avenue      f
David Johnson     41   103   80000       789 Oak Lane      m
Sarah Williams    29   104   55000      321 Pine Road      f
Michael Brown     35   105   70000    654 Maple Drive      m
Emily Davis       24   106   45000   987 Cedar Street      f
James Wilson      38   107   75000    543 Birch Court      m
Jennifer Taylor   31   108   60000    876 Walnut Lane      m
Robert Anderson   26   109   48000  234 Spruce Avenue      m
Jessica Thomas    33   110   68000    567 Cherry Lane      f

In [165]:
#Adding multiple columns in data frames..
df[['Height', 'Weight']] = [['5.1 ft','11 kg'],
                            ['5 ft','11 kg'],
                            ['5.3 ft','12 kg'],
                            ['5 ft','13 kg'],
                            ['5.5 ft','14 kg'],
                            ['5 ft','16 kg'],
                            ['5 ft','17 kg'],
                            ['6 ft','18 kg'],
                            ['5 ft','19 kg'],
                            ['4 ft','15 kg']]

df

                 Age  Roll  Salary            Address Gender  Height Weight
Name
John Doe          27   101   50000    123 Main Street      m  5.1 ft  11 kg
Jane Smith        32   102   65000     456 Elm Avenue      f    5 ft  11 kg
David Johnson     41   103   80000       789 Oak Lane      m  5.3 ft  12 kg
Sarah Williams    29   104   55000      321 Pine Road      f    5 ft  13 kg
Michael Brown     35   105   70000    654 Maple Drive      m  5.5 ft  14 kg
Emily Davis       24   106   45000   987 Cedar Street      f    5 ft  16 kg
James Wilson      38   107   75000    543 Birch Court      m    5 ft  17 kg
Jennifer Taylor   31   108   60000    876 Walnut Lane      m    6 ft  18 kg
Robert Anderson   26   109   48000  234 Spruce Avenue      m    5 ft  19 kg
Jessica Thomas    33   110   68000    567 Cherry Lane      f    4 ft  15 kg

In [167]:
# dropping multiple column in dataframe.
df=df.drop(columns=['Height','Weight','Gender'])
df

                 Age  Roll  Salary            Address
Name
John Doe          27   101   50000    123 Main Street
Jane Smith        32   102   65000     456 Elm Avenue
David Johnson     41   103   80000       789 Oak Lane
Sarah Williams    29   104   55000      321 Pine Road
Michael Brown     35   105   70000    654 Maple Drive
Emily Davis       24   106   45000   987 Cedar Street
James Wilson      38   107   75000    543 Birch Court
Jennifer Taylor   31   108   60000    876 Walnut Lane
Robert Anderson   26   109   48000  234 Spruce Avenue
Jessica Thomas    33   110   68000    567 Cherry Lane

In [168]:
# Exporting the dataframe into excel,csv ant txt file.


dict={'name':['miraj','sabal','sarita','rashmi','sabnam'],
      'roll':[1,2,3,4,5],'age':[13,34,32,54,32]}
df=pd.DataFrame(dict)
df

     name  roll  age
0   miraj     1   13
1   sabal     2   34
2  sarita     3   32
3  rashmi     4   54
4  sabnam     5   32

In [169]:
# Exporting the dataframe into excel file
df.to_excel('export_into_excel.xlsx',index=False)# if i want to run this in it i have to erite some code,ask to gpt

In [170]:
#Exporting the data frame into csv file
df.to_csv('export_into_csv.csv' ,index=False)

In [171]:
# Exporting the data frame into txt file
df.to_csv( 'export_into_txt.txt' ,index=False)

In [ ]:
# Understanding loc and iloc

# LOC--retrives data based on  labels(rows and columns names)
# df.loc[1:3,'name':'roll']
# --label-based indexing
# --the stop value is inclusive in slicing
# --includes rows 1 to 3 and columns from 'name' to 'roll'.


# # ILOC--retrives data based on integer positions (indices)
# df.iloc[1:4, o:2]
# --index-based slicing
# --the stop value is exclusive in slicing
# --includes rows 1 to 3  and columns 0 to 1

In [172]:
df = pd.read_excel(r"C:\Users\onc\Downloads\example 1 (1).xlsx" )
df.set_index('Name',inplace=True) 
df

                 Age  Roll  Salary            Address
Name
John Doe          27   101   50000    123 Main Street
Jane Smith        32   102   65000     456 Elm Avenue
David Johnson     41   103   80000       789 Oak Lane
Sarah Williams    29   104   55000      321 Pine Road
Michael Brown     35   105   70000    654 Maple Drive
Emily Davis       24   106   45000   987 Cedar Street
James Wilson      38   107   75000    543 Birch Court
Jennifer Taylor   31   108   60000    876 Walnut Lane
Robert Anderson   26   109   48000  234 Spruce Avenue
Jessica Thomas    33   110   68000    567 Cherry Lane

In [175]:
#using loc for row df.loc[row,column]
df.loc['John Doe']

Age                     27
Roll                   101
Salary               50000
Address    123 Main Street
Name: John Doe, dtype: object

In [178]:
#using loc to get value
df.loc['John Doe','Salary'] #df.loc[row,column]

np.int64(50000)

In [179]:
# multiple column chaiye list vitra halne
df.loc['John Doe',['Salary','Address']]#df.loc[row,column]

Salary               50000
Address    123 Main Street
Name: John Doe, dtype: object

In [182]:
# Slicing row,[2,7] ma 7 samma janxa in loc
df.loc['John Doe' : 'Michael Brown'] #df.loc[2:7],it goes upto 7.

                Age  Roll  Salary          Address
Name
John Doe         27   101   50000  123 Main Street
Jane Smith       32   102   65000   456 Elm Avenue
David Johnson    41   103   80000     789 Oak Lane
Sarah Williams   29   104   55000    321 Pine Road
Michael Brown    35   105   70000  654 Maple Drive

In [183]:
# Getting multiple values from the dataframe using loc...
df.loc['Jane Smith': 'David Johnson','Age':'Roll']

               Age  Roll
Name
Jane Smith      32   102
David Johnson   41   103

In [184]:
# jane dekhi david samma ko age ra address matra chaiye
df.loc['Jane Smith': 'David Johnson',['Age','Address']]

               Age         Address
Name
Jane Smith      32  456 Elm Avenue
David Johnson   41    789 Oak Lane

In [188]:
# getting multiple values from the dataframe using loc
df.loc['Jane Smith': 'David Johnson',['Age','Roll']]

               Age  Roll
Name
Jane Smith      32   102
David Johnson   41   103

In [189]:
#getting multiple values from the dataframe  using loc..
df.loc['Jane Smith':'David Johnson','Age':'Roll']

               Age  Roll
Name
Jane Smith      32   102
David Johnson   41   103

In [190]:
df

                 Age  Roll  Salary            Address
Name
John Doe          27   101   50000    123 Main Street
Jane Smith        32   102   65000     456 Elm Avenue
David Johnson     41   103   80000       789 Oak Lane
Sarah Williams    29   104   55000      321 Pine Road
Michael Brown     35   105   70000    654 Maple Drive
Emily Davis       24   106   45000   987 Cedar Street
James Wilson      38   107   75000    543 Birch Court
Jennifer Taylor   31   108   60000    876 Walnut Lane
Robert Anderson   26   109   48000  234 Spruce Avenue
Jessica Thomas    33   110   68000    567 Cherry Lane

In [192]:
#104 ra 105 matra chaiyo rey aba
df.loc[['Sarah Williams','Michael Brown'],'Roll']

Name
Sarah Williams    104
Michael Brown     105
Name: Roll, dtype: int64

In [193]:
df.iloc[3:5,1]

Name
Sarah Williams    104
Michael Brown     105
Name: Roll, dtype: int64

In [194]:
# we can convert any row or column into list
list(df['Roll'])

[101, 102, 103, 104, 105, 106, 107, 108, 109, 110]

In [ ]:
list(df.loc['John Doe'])

In [ ]:
#Handling missing data in data frame....

In [199]:
#drop
df = pd.DataFrame({
    'SN':[1.0,2.0,3.0,4.0,np.nan,6.0],
    'Age':[32,5,42,37,29,31],
    'Roll':[12,13,14,np.nan,15,16],
    'Employee ID':[1002.0,122.0,133.0,111.0,234.0,345.0],
    'Name':[np.nan,'Jane Smith','David Brown','Lisa Green','Mark Davis','Anna']
    })
df

    SN  Age  Roll  Employee ID         Name
0  1.0   32  12.0       1002.0          NaN
1  2.0    5  13.0        122.0   Jane Smith
2  3.0   42  14.0        133.0  David Brown
3  4.0   37   NaN        111.0   Lisa Green
4  NaN   29  15.0        234.0   Mark Davis
5  6.0   31  16.0        345.0         Anna

In [200]:
#check if the values are null
df.isnull()

      SN    Age   Roll  Employee ID   Name
0  False  False  False        False   True
1  False  False  False        False  False
2  False  False  False        False  False
3  False  False   True        False  False
4   True  False  False        False  False
5  False  False  False        False  False

In [201]:
# We can remove the missing values from specific columns
df['Name'].dropna() #o index nan is removed

1     Jane Smith
2    David Brown
3     Lisa Green
4     Mark Davis
5           Anna
Name: Name, dtype: object

In [202]:

df[['Name','Roll']].dropna() # removing the nan values from the name and roll column..

          Name  Roll
1   Jane Smith  13.0
2  David Brown  14.0
4   Mark Davis  15.0
5         Anna  16.0

In [203]:
#filling

df = pd.DataFrame({
    'SN':[1.0,2.0,3.0,4.0,np.nan,6.0],
    'Age':[32,5,42,37,29,31],
    'Roll':[12,13,14,np.nan,15,16],
    'Employee ID':[1002.0,122.0,133.0,111.0,234.0,345.0],
    'Name':[np.nan,'Jane Smith','David Brown','Lisa Green','Mark Davis','Anna']
    })
df

    SN  Age  Roll  Employee ID         Name
0  1.0   32  12.0       1002.0          NaN
1  2.0    5  13.0        122.0   Jane Smith
2  3.0   42  14.0        133.0  David Brown
3  4.0   37   NaN        111.0   Lisa Green
4  NaN   29  15.0        234.0   Mark Davis
5  6.0   31  16.0        345.0         Anna

In [204]:
#filling all the missing fields with 4
df.fillna(4)

    SN  Age  Roll  Employee ID         Name
0  1.0   32  12.0       1002.0            4
1  2.0    5  13.0        122.0   Jane Smith
2  3.0   42  14.0        133.0  David Brown
3  4.0   37   4.0        111.0   Lisa Green
4  4.0   29  15.0        234.0   Mark Davis
5  6.0   31  16.0        345.0         Anna

In [206]:
df['Roll'].fillna(0.0)

0    12.0
1    13.0
2    14.0
3     0.0
4    15.0
5    16.0
Name: Roll, dtype: float64

In [207]:
# We can also give mean value to empty field like this
df['SN'].fillna(df['SN'].mean()) #SN ko mean nikalera fillna ma as a argument value pass gardinxa

0    1.0
1    2.0
2    3.0
3    4.0
4    3.2
5    6.0
Name: SN, dtype: float64

In [220]:
#handling the duplicated values
import numpy as np
df = pd.DataFrame({
    'SN':[1.0,1.0,3.0,4.0,np.nan,6.0],
    'Age':[32,32,42,37,29,31],
    'Roll':[12,12,14,np.nan,15,16],
    'Employee ID':[1002.0,1002.0,133.0,111.0,234.0,345.0],
    'Name':['Jane Smith','Jane Smith','David Brown','Lisa Green','Mark Davis','Anna']
    })
df

    SN  Age  Roll  Employee ID         Name
0  1.0   32  12.0       1002.0   Jane Smith
1  1.0   32  12.0       1002.0   Jane Smith
2  3.0   42  14.0        133.0  David Brown
3  4.0   37   NaN        111.0   Lisa Green
4  NaN   29  15.0        234.0   Mark Davis
5  6.0   31  16.0        345.0         Anna

In [221]:
df.duplicated()

0    False
1     True
2    False
3    False
4    False
5    False
dtype: bool

In [222]:
df[df.duplicated()]

    SN  Age  Roll  Employee ID        Name
1  1.0   32  12.0       1002.0  Jane Smith

In [223]:
df.drop_duplicates(inplace=True)
df

    SN  Age  Roll  Employee ID         Name
0  1.0   32  12.0       1002.0   Jane Smith
2  3.0   42  14.0        133.0  David Brown
3  4.0   37   NaN        111.0   Lisa Green
4  NaN   29  15.0        234.0   Mark Davis
5  6.0   31  16.0        345.0         Anna

In [224]:
df

    SN  Age  Roll  Employee ID         Name
0  1.0   32  12.0       1002.0   Jane Smith
2  3.0   42  14.0        133.0  David Brown
3  4.0   37   NaN        111.0   Lisa Green
4  NaN   29  15.0        234.0   Mark Davis
5  6.0   31  16.0        345.0         Anna

In [225]:
#to see the non duplicate value we can use not(~)
~df.duplicated()

0    True
2    True
3    True
4    True
5    True
dtype: bool

In [226]:
#to check unique value in each column
df.nunique()#give count of unique valaue in each row

SN             4
Age            5
Roll           4
Employee ID    5
Name           5
dtype: int64

In [ ]:
# Checking conditions in to filter data

In [227]:
# checking if Name column have miraj or not..
df['Name']=='miraj'

0    False
2    False
3    False
4    False
5    False
Name: Name, dtype: bool

In [228]:
# To check multiple conditions 
df[(df['Age']==31)&(df['SN']>5)]

    SN  Age  Roll  Employee ID  Name
5  6.0   31  16.0        345.0  Anna

In [229]:
# Delete specific row and column
df

    SN  Age  Roll  Employee ID         Name
0  1.0   32  12.0       1002.0   Jane Smith
2  3.0   42  14.0        133.0  David Brown
3  4.0   37   NaN        111.0   Lisa Green
4  NaN   29  15.0        234.0   Mark Davis
5  6.0   31  16.0        345.0         Anna

In [231]:
df.index=['1st','2nd','3rd','4th','5th']
df

      SN  Age  Roll  Employee ID         Name
1st  1.0   32  12.0       1002.0   Jane Smith
2nd  3.0   42  14.0        133.0  David Brown
3rd  4.0   37   NaN        111.0   Lisa Green
4th  NaN   29  15.0        234.0   Mark Davis
5th  6.0   31  16.0        345.0         Anna

In [232]:
# to delete the specific row
df.drop(labels='1st')

      SN  Age  Roll  Employee ID         Name
2nd  3.0   42  14.0        133.0  David Brown
3rd  4.0   37   NaN        111.0   Lisa Green
4th  NaN   29  15.0        234.0   Mark Davis
5th  6.0   31  16.0        345.0         Anna

In [234]:
df.drop(labels=['1st','2nd'])

      SN  Age  Roll  Employee ID        Name
3rd  4.0   37   NaN        111.0  Lisa Green
4th  NaN   29  15.0        234.0  Mark Davis
5th  6.0   31  16.0        345.0        Anna

In [235]:
# To delete the specific column
df.drop(columns='Name')

      SN  Age  Roll  Employee ID
1st  1.0   32  12.0       1002.0
2nd  3.0   42  14.0        133.0
3rd  4.0   37   NaN        111.0
4th  NaN   29  15.0        234.0
5th  6.0   31  16.0        345.0

In [236]:
# to delete the specific column or row by another axis methods,  0-row,1-column...
#delete column
df.drop('Age',axis=1)

      SN  Roll  Employee ID         Name
1st  1.0  12.0       1002.0   Jane Smith
2nd  3.0  14.0        133.0  David Brown
3rd  4.0   NaN        111.0   Lisa Green
4th  NaN  15.0        234.0   Mark Davis
5th  6.0  16.0        345.0         Anna

In [237]:
#deleting row
df.drop('4th', axis=0)

      SN  Age  Roll  Employee ID         Name
1st  1.0   32  12.0       1002.0   Jane Smith
2nd  3.0   42  14.0        133.0  David Brown
3rd  4.0   37   NaN        111.0   Lisa Green
5th  6.0   31  16.0        345.0         Anna

In [238]:
df.drop(columns=['Age','Employee ID','Name'], inplace=True)
df

      SN  Roll
1st  1.0  12.0
2nd  3.0  14.0
3rd  4.0   NaN
4th  NaN  15.0
5th  6.0  16.0

In [239]:
#To concat dataframes

df1=pd.DataFrame({'Name':['miraj','aman'],'Roll':[10,11]})
df2=pd.DataFrame({'Name':['arbit','amir'],'Roll':[15,13]})
df3=pd.DataFrame({'Name':['june','july'],'Roll':[18,21]})
df=pd.concat([df1,df2,df3])
df

    Name  Roll
0  miraj    10
1   aman    11
0  arbit    15
1   amir    13
0   june    18
1   july    21

In [240]:
df=pd.concat([df1,df2,df3],keys=['group1','group2','group3'],names=['group','rowno'])
df

               Name  Roll
group  rowno
group1 0      miraj    10
       1       aman    11
group2 0      arbit    15
       1       amir    13
group3 0       june    18
       1       july    21

In [241]:
# String Operation in the dataframe

# Create a sample DataFrame
df = pd.DataFrame({'name': ['John', 'Alice', 'Bob'],
'salary': ['10,000', '5,500', '8,750']})
# Remove commas from 'salary' column
#data frame ko sab element ko comma hatxa
df['salary'] = df['salary'].str.replace(',', '')
# Display the updated DataFrame
df

    name salary
0   John  10000
1  Alice   5500
2    Bob   8750