# Pandas Exercise: Student Dataset Analysis

In this exercise, you will practice using various Pandas methods to explore, clean, and manipulate a student dataset. 

### Prerequisites
Ensure you have the `student_data_english.csv` file in the same directory as this notebook.

### 1. Load the Dataset
Import pandas and load the `student_data_english.csv` file into a DataFrame named `df`.

In [1]:
import pandas as pd

df = pd.read_csv(r"C:\Users\Acer\Desktop\Training\student_data_english.csv")

### 2. Basic Exploration
**Q: Use to first 5 and last 5 rows in data set**

In [2]:
df.head()

   roll_no          name   address   age gender     hobby     iq pass_status
0       15         Suman  Lalitpur  24.0  Other   Reading   89.0        Fail
1       17         Suman  Birtamod  24.0  Other   Cricket  114.0        Pass
2       94  Laxmi Gurung  Rajbiraj  17.0   Male  Painting   88.0        Pass
3        4   Bishnu Maya      Beni  23.0  Other   Cycling  122.0        Fail
4       22   Bishnu Maya    Balewa  17.0   Male      Yoga   97.0        Fail

In [3]:
df.tail()

,roll_no,name,address,age,gender,hobby,iq,pass_status
103,54,Deepak,Biratnagar,16.0,Other,Swimming,133.0,Pass
104,85,Vikas,Kathmandu,17.0,Other,Video Games,123.0,Fail
105,78,Narayan Gopal,Lahan,21.0,Female,Video Games,122.0,Pass
106,71,NaN,Baglung,16.0,Other,Playing Flute,123.0,Pass
107,47,NaN,Kushma,NaN,Other,Singing,86.0,Fail

**Q: Use to see the dataset structure and data types.**

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 108 entries, 0 to 107
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   roll_no      108 non-null    int64
 1   name         100 non-null    str
 2   address      100 non-null    str
 3   age          104 non-null    float64
 4   gender       107 non-null    str
 5   hobby        103 non-null    str
 6   iq           106 non-null    float64
 7   pass_status  107 non-null    str
dtypes: float64(2), int64(1), str(5)
memory usage: 6.9 KB

**Q: Use to get statistical summaries of the numerical columns.**

In [8]:
df.describe()

          roll_no         age          iq
count  108.000000  104.000000  106.000000
mean    49.750000   20.326923  109.707547
std     29.811283    3.307662   17.039990
min      1.000000   15.000000   80.000000
25%     23.750000   17.000000   96.000000
50%     49.500000   20.000000  110.500000
75%     76.250000   23.000000  123.000000
max    100.000000   25.000000  140.000000

### 3. Handling Null Values
**Q: Check for null values in the entire DataFrame using and count them per column.**

In [9]:
df.isnull().sum()

roll_no        0
name           8
address        8
age            4
gender         1
hobby          5
iq             2
pass_status    1
dtype: int64

**Show all rows with an empty value in the name column.**

In [10]:
df[df['name'].isnull()]

,roll_no,name,address,age,gender,hobby,iq,pass_status
7,2,NaN,Mahendranagar,23.0,Female,Yoga,133.0,Fail
20,79,NaN,Beni,15.0,Other,Football,132.0,Fail
29,6,NaN,Lalitpur,23.0,Male,Dancing,131.0,Pass
57,66,NaN,NaN,20.0,Male,Traveling,92.0,Pass
83,80,NaN,Birgunj,25.0,Other,Playing Flute,132.0,Pass
101,27,NaN,Birtamod,22.0,Female,Chess,118.0,Fail
106,71,NaN,Baglung,16.0,Other,Playing Flute,123.0,Pass
107,47,NaN,Kushma,NaN,Other,Singing,86.0,Fail

**Q: Remove rows where the name column is null.**

In [11]:
df = df[~df['name'].isnull()] # df.dropna(subset=[''])

**Show all rows with an empty value in the age column.**

In [12]:
df[df['age'].isnull()] #roll - 35,60,65

    roll_no    name        address  age  gender     hobby     iq pass_status
41       35   Suman      Kathmandu  NaN  Female   Reading   88.0        Fail
56       60  Sunita      Kathmandu  NaN     NaN  Football  101.0        Pass
93       65   Nisha  Mahendranagar  NaN    Male  Painting  101.0        Fail

**Q: Impute missing values in the age column with the mean age.**

In [ ]:
df['age']=df['age'].fillna(int(df['age'].mean()))

**Q: After imputing the missing values, display the rows with roll_no 35, 60, and 65, which previously had missing values.**

In [ ]:
df[(df['roll_no']==35)|(df['roll_no']==60)|(df['roll_no']==65)]

**Q: See again the count of null values per column**

In [ ]:
df.isnull().sum()

**Q. Show all rows with an empty value in the gender column.**

In [ ]:
df[df['gender'].isnull()]

**Q: Fill missing values in the gender column using the mode.**

In [ ]:
df['gender'] = df['gender'].fillna(df['gender'].mode()[0]) # roll-> 60

**Q: After imputing the missing values, display the rows with 60 which previously had missing gender values.**

In [13]:
df.query('roll_no == 60')

    roll_no    name    address  age gender     hobby     iq pass_status
56       60  Sunita  Kathmandu  NaN    NaN  Football  101.0        Pass

**Q: Drop all other null rows permanently.**

In [ ]:
df.dropna(inplace=True)

### 4. Handling Duplicates

**Q: Count duplicate rows**

In [14]:
df.duplicated().sum()

np.int64(3)

**Q: Identify duplicate rows in the dataset.**

In [15]:
df[df.duplicated()]

    roll_no         name     address   age gender    hobby     iq pass_status
66        4  Bishnu Maya        Beni  23.0  Other  Cycling  122.0        Fail
87       92       Ramesh  Biratnagar  17.0  Other    Chess  118.0        Pass
97       92       Ramesh  Biratnagar  17.0  Other    Chess  118.0        Pass

**Q: Drop the duplicate rows from the DataFrame.**

In [17]:
df=df.drop_duplicates()

### 5. Column Operations
**Q: Rename the column `roll_no` to `Student_ID`.**

In [19]:
new_name= {'roll_no': 'Student_ID'}

df.rename(columns=new_name, inplace=True)

**Q: Drop the `hobby` column permanently from the DataFrame.**

In [20]:
df.drop(columns=['hobby'], inplace=True) # df.drop(['hobby'], axis=1, inplace=True)

### 6. Unique Values and Frequencies
**Q: Find the number of unique values in the `address` column.**

In [21]:
df['address'].nunique()

28

**Q: See the distribution of students by `gender`.**

In [22]:
df['gender'].value_counts()

gender
Other     37
Female    32
Male      27
Name: count, dtype: int64

### 7. Filtering and Sorting
**Q: Filter the DataFrame to show only students who have an `iq` greater than 120.**

In [24]:
df[df['iq'] > 120].sort_values(by='iq', ascending=False)

     Student_ID           name        address   age  gender     iq pass_status
21           13      Tara Devi        Pokhara  24.0  Female  140.0        Pass
49           57          Manoj  Mahendranagar  24.0  Female  138.0        Pass
42           23        Ranjana       Birtamod  17.0   Other  136.0        Fail
85           88      Saraswati       Janakpur  23.0   Other  135.0        Pass
70           59   Rajesh Hamal        Baglung  18.0    Male  135.0        Fail
89           14         Suresh      Bharatpur  18.0    Male  135.0        Fail
8            50           Ajay       Rajbiraj  19.0    Male  134.0        Fail
103          54         Deepak     Biratnagar  16.0   Other  133.0        Pass
9            10         Ganesh      Nepalgunj  25.0    Male  133.0        Pass
40           10         Ganesh            NaN  25.0    Male  133.0        Pass
32           52        Ranjana       Lalitpur  24.0  Female  132.0        Fail
34           97          Vikas        Hetauda  22.0   Other  131.0        Fail
19           99         Vishal         Butwal  19.0   Other  130.0        Pass
22           34    Bishnu Maya       Lalitpur  17.0    Male  129.0        Fail
5            63          Sapna     Biratnagar  19.0    Male  129.0        Fail
38           83   Laxmi Gurung         Tansen  24.0   Other  128.0        Fail
84           91           Ritu         Tansen  16.0    Male  127.0        Fail
74           98          Anita     Biratnagar  20.0  Female  126.0        Pass
77           41          Priya       Tulsipur  18.0   Other  126.0        Fail
51           68  Santosh Magar       Rajbiraj  21.0   Other  126.0        Pass
55           42         Sunita           Beni  19.0  Female  124.0        Pass
104          85          Vikas      Kathmandu  17.0   Other  123.0        Fail
64           44          Manoj         Waling  24.0  Female  123.0        Fail
24            3         Ganesh         Kushma  17.0    Male  123.0        Pass
11           84           Ajay       Lalitpur  20.0    Male  122.0        Pass
3             4    Bishnu Maya           Beni  23.0   Other  122.0        Fail
43           78  Narayan Gopal          Lahan  21.0  Female  122.0        Pass
72           46        Manisha      Nepalgunj  17.0   Other  122.0        Fail
105          78  Narayan Gopal          Lahan  21.0  Female  122.0        Pass

**Q: Sort the DataFrame by `age` in descending order.**

In [ ]:
df.sort_values(by='age', ascending=False)

### 8. Indexing with `loc` and `iloc` (Advanced)

**Q1: Use `loc` to select the `name` and `pass_status` for students at index labels 10 to 20.**

In [26]:
df.loc[10:20,['name','pass_status']]

           name pass_status
10  Bishnu Maya        Fail
11         Ajay        Pass
12        Sapna         NaN
13         Ritu        Fail
14  Sita Kumari        Fail
15      Parijat        Pass
16        Pawan        Pass
17   Gita Thapa        Pass
18       Suresh        Pass
19       Vishal        Pass

**Q2: Use `loc` to select all rows where `address` is 'Kathmandu' and only display `name` and `age` columns.**

In [27]:
df[df['address']=="Kathmandu"].loc[:,["name","age"]]

           name   age
17   Gita Thapa  22.0
41        Suman   NaN
56       Sunita   NaN
104       Vikas  17.0

**Q3: Use `iloc` to select the first 5 rows and the first 3 columns of the DataFrame.**

In [28]:
df.iloc[:5,:3]

   Student_ID          name   address
0          15         Suman  Lalitpur
1          17         Suman  Birtamod
2          94  Laxmi Gurung  Rajbiraj
3           4   Bishnu Maya      Beni
4          22   Bishnu Maya    Balewa

**Q4: Use `iloc` to select the last 2 rows and all columns.**

In [29]:
df.iloc[-2:,:] # - means start from the second-last row. : means go till the end.

     Student_ID           name    address   age  gender     iq pass_status
104          85          Vikas  Kathmandu  17.0   Other  123.0        Fail
105          78  Narayan Gopal      Lahan  21.0  Female  122.0        Pass

**Q5: Use `iloc` to select the value in the 2nd row and 4th column.**

In [31]:
df.iloc[2,4]

'Male'